apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-consumer
  labels:
    app: simple-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-consumer
  template:
    metadata:
      labels:
        app: simple-consumer
    spec:
      containers:
      - name: simple-consumer
        image: 576962245852.dkr.ecr.us-east-1.amazonaws.com/simple-consumer:latest